name: "Hugo Build & Audit"
description: "Checkout, build, and audit a Hugo site"
inputs:
  do-minify:
    description: "If present, minify site using --minify during build"
    required: false
  go-version:
    description: "Go Version"
    required: true
    default: "^1.17.3"
  hugo-env:
    description: "Hugo environment (production, development, etc)"
    required: true
    default: "production"
  source-directory:
    description: "Where the source for the site lives"
    required: false
  hugo-version:
    description: "Hugo Version"
    required: true
    default: "0.89.4"
  upload-html-validate-config:
    description: "If present, include config for html-validate in artifact (if present)"
    required: false
  upload-output-directory:
    description: "Output directory to upload (default 'public')"
    required: true
    default: "public"
  upload-site-as:
    description: "Artifact to create containing the Hugo site"
    required: false
  upload-site-retention:
    description: "Retention period in days for Hugo site artifact"
    required: false
    default: "1"
  use-lfs:
    description: "Use LFS when checkout out repo"
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        lfs: ${{ inputs.use-lfs }}
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - shell: bash
      env:
        HUGO_VER: ${{ inputs.hugo-version }}
      run: curl -sL "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz" -o hugo.tar.gz
    - shell: bash
      run: sudo tar -C /usr/local/bin -xzf hugo.tar.gz hugo
    - shell: bash
      env:
        HUGO_MINIFY_TDEWOLFF_HTML_KEEPCOMMENTS: "true"
        HUGO_ENABLEMISSINGTRANSLATIONPLACEHOLDERS: "true"
        HUGO_ENV: ${{ inputs.hugo-env }}
        INPUT_DO_MINIFY: ${{ inputs.do-minify }}
        SOURCE_DIRECTORY: ${{ inputs.source-directory }}
      run: hugo ${SOURCE_DIRECTORY:+-s "$SOURCE_DIRECTORY"} --gc --cleanDestinationDir ${INPUT_DO_MINIFY:+--minify}; fi
    - shell: bash
      run: |
        set -o pipefail; \
        if grep -iIvrnE "grep(.+(-- raw HTML omitted --|ZgotmplZ|hahahugo|\\\[i18n\\\])+)" public/ | \
        grep -iIoE "<\!-- raw HTML omitted -->|ZgotmplZ|hahahugo|\[i18n\]"; then \
        echo "not ok"; exit 1; else echo "ok"; exit 0; fi
    - shell: bash
      env:
        HUGO_ENV: ${{ inputs.hugo-env }}
        INPUT_DO_MINIFY: ${{ inputs.do-minify }}
        INPUT_OUTPUT_DIRECTORY: ${{ inputs.output-directory }}
        INPUT_NO_UPLOAD_HTML_VALIDATE_CONFIG: ${{ inputs.no-upload-html-validate-config }}
        SOURCE_DIRECTORY: ${{ inputs.source-directory }}
      run: hugo ${SOURCE_DIRECTORY:+-s "$SOURCE_DIRECTORY"} --gc --cleanDestinationDir ${INPUT_DO_MINIFY:+--minify}; fi
    - shell: bash
      run: tar -cf hugo-site.tar "${INPUT_OUTPUT_DIRECTORY}" ${INPUT_UPLOAD_HTML_VALIDATE_CONFIG:+.htmlvalidate*}; else tar -cf hugo-site.tar "${INPUT_OUTPUT_DIRECTORY}"; fi
    - uses: actions/upload-artifact@v2
      if: inputs.upload-site-as
      with:
        name: ${{ inputs.upload-site-as }}
        path: hugo-site.tar
        if-no-files-found: error
        retention-days: ${{ inputs.upload-site-retention }}
