name: "Hugo Build & Audit"
description: "Checkout, build, and audit a Hugo site"
inputs:
  checkout-fetch-depth:
    description: "Fetch depth: Use 0 to fetch all history if using .GitInfo or .Lastmod"
    required: true
    default: "0"
  checkout-submodules:
    description: "Fetch git submodules: false, true, or recursive"
    required: true
    default: "false"
  do-minify:
    description: "If present, minify site using --minify during build"
    required: false
  hugo-env:
    description: "Hugo environment (production, development, etc)"
    required: true
    default: "production"
  hugo-extended:
    description: "Hugo Extended"
    required: true
    default: "true"
  hugo-version:
    description: "Hugo Version"
    required: true
    default: "0.89.4"
  output-directory:
    description: "Location of output site"
    required: true
    default: "public"
  source-directory:
    description: "Where the source for the site lives"
    required: false
  upload-html-validate-config:
    description: "If present, include config for html-validate in artifact (if present)"
    required: false
  upload-npm-json:
    description: "If present, include package.json and package-lock.json in artifact"
    required: false
  upload-site-as:
    description: "Artifact to create containing the Hugo site"
    required: false
  upload-site-retention:
    description: "Retention period in days for Hugo site artifact"
    required: false
    default: "1"
  use-lfs:
    description: "Use LFS when checking out out repo"
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        lfs: ${{ inputs.use-lfs }}
        submodules: ${{ inputs.submodules }}
        fetch-depth: ${{ inputs.checkout-fetch-depth }}
    - name: "Install Hugo"
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ inputs.hugo-version }}
        extended: ${{ inputs.hugo-extended }}
    - name: "Hugo modules cache"
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/hugo_cache
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-
    - name: "Pull Hugo modules before calculating resources"
      shell: bash
      env:
        SOURCE_DIRECTORY: ${{ github.workspace }}/${{ inputs.source-directory }}
        HUGO_CACHEDIR: ${{ github.workspace }}/hugo_cache
      run: hugo mod tidy --source ${SOURCE_DIRECTORY}
    - name: "Hugo resources cache"
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/${{ inputs.source-directory }}/resources
        key: ${{ runner.os }}-hugoresources-${{ hashFiles('**/assets/**', '**.webp', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.tiff', '**.tif', '**.bmp') }}
        restore-keys: |
          ${{ runner.os }}-hugoresources-
          ${{ runner.os }}-hugoresources
    - name: "Build site so it is suitable for auditing"
      shell: bash
      env:
        DO_MINIFY: ${{ inputs.do-minify }}
        HUGO_CACHEDIR: ${{ github.workspace }}/hugo_cache
        HUGO_ENABLEMISSINGTRANSLATIONPLACEHOLDERS: "true"
        HUGO_ENV: ${{ inputs.hugo-env }}
        HUGO_MINIFY_TDEWOLFF_HTML_KEEPCOMMENTS: "true"
        OUTPUT_DIRECTORY: ${{ github.workspace }}/${{ inputs.output-directory }}
        SOURCE_DIRECTORY: ${{ github.workspace }}/${{ inputs.source-directory }}
      run: hugo ${SOURCE_DIRECTORY:+-s "$SOURCE_DIRECTORY"} -d "${OUTPUT_DIRECTORY}" --gc --cleanDestinationDir ${DO_MINIFY:+--minify}
    - name: "Audit site for missed Hugo issues"
      shell: bash
      env:
        OUTPUT_DIRECTORY: ${{ github.workspace }}/${{ inputs.output-directory }}
      run: if test "$(grep -iIvrnE 'grep(.+(-- raw HTML omitted --|ZgotmplZ|hahahugo|\\\[i18n\\\])+)' "${OUTPUT_DIRECTORY}" | grep -iIoE '<\!-- raw HTML omitted -->|ZgotmplZ|hahahugo|\[i18n\]')" != ""; then echo "not ok"; exit 1; else echo "ok"; exit 0; fi
    - name: "Build site without audit markup"
      if: inputs.upload-site-as
      shell: bash
      env:
        DO_MINIFY: ${{ inputs.do-minify }}
        HUGO_CACHEDIR: ${{ github.workspace }}/hugo_cache
        HUGO_ENV: ${{ inputs.hugo-env }}
        OUTPUT_DIRECTORY: ${{ github.workspace }}/${{ inputs.output-directory }}
        SOURCE_DIRECTORY: ${{ github.workspace }}/${{ inputs.source-directory }}
      run: hugo ${SOURCE_DIRECTORY:+-s "$SOURCE_DIRECTORY"} -d "${OUTPUT_DIRECTORY}" --gc --cleanDestinationDir ${DO_MINIFY:+--minify}
    - name: "Bundle site for upload as artifact"
      if: inputs.upload-site-as
      shell: bash
      env:
        OUTPUT_DIRECTORY: ${{ github.workspace }}/${{ inputs.output-directory }}
        SOURCE_DIRECTORY: ${{ github.workspace }}/${{ inputs.source-directory }}
        UPLOAD_HTML_VALIDATE_CONFIG: ${{ inputs.upload-html-validate-config }}
        UPLOAD_NPM_JSON: ${{ inputs.upload-npm-json }}
      run: tar -cf hugo-site.tar "${OUTPUT_DIRECTORY}" ${UPLOAD_HTML_VALIDATE_CONFIG:+.htmlvalidate*} ${UPLOAD_NPM_JSON:+package.json package-lock.json}
    - name: "Upload site as an artifact"
      uses: actions/upload-artifact@v2
      if: inputs.upload-site-as
      with:
        name: ${{ inputs.upload-site-as }}
        path: hugo-site.tar
        if-no-files-found: error
        retention-days: ${{ inputs.upload-site-retention }}
