name: test-build-audit
on:
  pull_request:
  push:
    branches:
      - main
      - staging-**
jobs:
  do-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: ./
        with:
          source-directory: src

